import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Menu from "@/components/Menu";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <header className="flex items-center justify-between p-4 bg-gray-900">
          <Link href="/" className="text-lg font-bold">NoLossToken </Link>
          <Menu />
        </header>
        <main className="flex-grow">
          <NextSSRPlugin
            /**
             * The `extractRouterConfig` will extract **only** the route configs
             * from the router to prevent additional information from being
             * leaked to the client. The data passed to the client is the same
             * as if you were to fetch `/api/uploadthing` directly.
             */
            routerConfig={extractRouterConfig(ourFileRouter)}
          />
          {children}
        </main>
        <footer className="bg-gray-900 text-center py-4">
          <p className="text-sm">© 2024 NoLossToken . All rights reserved.</p>
          <div className="mt-2">
            <a href="#" className="hover:underline">Terms</a> |
            <a href="#" className="hover:underline">Privacy</a> |
            <a href="#" className="hover:underline">Docs</a>
          </div>
        </footer>
      </body>
    </html>
  );
}
